# -*- coding: utf-8 -*-
"""1_DataFrame_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2ZTDqxgr3oqrT-IJrfdiCTwE_zqWwRk
"""

#!pip install langchain_openai

#!pip install langchain_experimental

from langchain.agents.agent_types import AgentType
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI

import pandas as pd
from langchain_openai import OpenAI

df = pd.read_csv(
    "https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/CardioGoodFitness-1.csv"
)

df.head()

from google.colab import userdata
import os
os.environ["OPENAI_API_KEY"]=userdata.get("sep_openai")

llm=OpenAI()

agent = create_pandas_dataframe_agent(llm, df, verbose=True, allow_dangerous_code=True)

len(df)

agent.run("How many rows are there?")

agent.run("How many columns are there?")

agent.run("How many People are using TM 798?")

agent.run("What is the maximum age?")



agent.run("What is the Fitness level whose age is 18")

agent.run("What is the fitness and gender of the person whose age is 18")

agent.run("Run KNN model and give the accuracy")

agent.run("What is the Problem Statement")

agent.run("What is the maximum fitness")

agent.run("Show the record of the eldest?")

agent.run("Why is TM798 sale less?")

agent.run("Is Fitness numerical or categorical?")

agent.run("You are wrong,idiot")

agent.run("Fitness is categorical but represented as numbers")

agent.run("Is fitness numerical or categorical?")

agent.run("Why is TM798 count less")

agent.run("Why?")

agent.run()